name: Check for recent changes
description: Check for recent changes in a public GitHub repository

inputs:
  repository:
    description: 'Which source repository (on GitHub) to check for changes'
    required: true
  branch:
    description: 'Which source branch to check for changes'
    required: false
    default: 'master'
  threshold:
    description: 'In which timeframe (in integer days) changes have to occur to trigger a build'
    required: false
    default: 2
outputs:
  days:
    description: "Days since the last change in the repository"
    value: ${{ steps.check_for_changes.outputs.days }}
  changes_exist:
    description: "='true' if recent changes exist within threshold"
    value: ${{ steps.check_for_changes.outputs.changes_exist }}

runs:
  using: "composite"
  steps:
  - name: Check for recent changes
    id: check_for_changes
    shell: bash
    env:
      CHECK_REPOSITORY: ${{ inputs.repository }}
      CHECK_BRANCH: ${{ inputs.branch }}
      CHECK_DAYS: ${{ inputs.threshold }}
    run: |
      echo "Workflog triggered by $GITHUB_EVENT_NAME"
      commitdate=$(curl -sL "https://api.github.com/repos/$CHECK_REPOSITORY/commits/$CHECK_BRANCH" | jq -r ".commit.author.date")
      commitdays=$(( ( $(date --utc +%s) - $(date --utc -d $commitdate +%s) ) / 86400 ))
      echo "::set-output name=days::$commitdays"
      echo "Last commit was $commitdays days ago."
      if [ $commitdays -lt $CHECK_DAYS ] || [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
        echo "::set-output name=changes_exist::true"
        echo "There ARE recent changes in the repository."
      else
        echo "::set-output name=changes_exist::false"
        echo "There are NO recent changes in the repository."
      fi
